language: c
jobs:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
    env: CONFIGURE_EXTRA=--with-sanitize=basic
  - os: osx
    compiler: clang
env:
  global:
  - secure: Ejc9hqPE/TQ1HiSao3FHZ8piTmpCVuQthPYUuFv8Yz7GDbia7yx85b9IHd17wVmg1rGHaFed9hvSesbfFu82h86NYLmnQJGvA4XAptpBw8Z3621U0ar2QXHuaY7uAaKdeAC5NwIS6/DiufEqGtQJrNNs+5pLEATGOuoO+QugdTI=
addons:
  apt:
    packages:
    - python-pip
    - build-essential
    - automake
    - autoconf
  coverity_scan:
    project:
      name: vifm/vifm
      version: 0.11+
      description: TUI file manager with vi like key bindings.
    notification_email: xaizek@posteo.net
    build_command_prepend: scripts/fix-timestamps fast && ./configure --disable-dependency-tracking
    build_command: make -j 3
    branch_pattern: coverity-scan
cache:
- pip
script:
- if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then scripts/fix-timestamps fast && ( if [
  "$CC" = gcc -a "$TRAVIS_OS_NAME" = linux ]; then pip install --user cpp-coveralls
  pyopenssl ndg-httpsclient pyasn1 && ./configure --disable-dependency-tracking --enable-coverage;
  else ./configure --disable-dependency-tracking $CONFIGURE_EXTRA; fi ) && make -j4
  && make check && ( if [ "$CC" = clang ] && [ "$TRAVIS_OS_NAME" = linux ] && [ -n "$TRAVIS_TAG"
  ]; then ./pkgs/AppImage/genappimage.sh; fi );
  fi
after_success:
- if [ "$COVERITY_SCAN_BRANCH" != 1 -a "$CC" = gcc ]; then coveralls --encoding iso-8859-1
  --build-root src/ --exclude tests --exclude src/lua/lua --exclude src/utils/parson.c
  --exclude src/utils/xxhash.c --gcov-options '\-p'; fi
notifications:
  email:
    recipients:
    - xaizek@posteo.net
deploy:
  provider: releases
  api_key:
    secure: OdkPjORbqrdIX8uy8RptWUa5AeTsU+ilnAhg6G8s+zf6zdQUcTU7aANK9l8BjtC63MNBWPt6dNvlyjEZzomWnaisn+ikS27HBt2gMecewybAKuehe6CuAJO9eP8UyIQUbac3N1VZMsz62tEUeNaBiKwUdt0ddRErXcP52BgIc3t1Kq3BbXsFbzNaDD2a+uXQ8hcMqY5abeml7Y8+OSOoYUo30tDDpVSBKNo/K6CK//DiQREEoSqgTJ46yS82b2yjHsB03ZxIRbAwCSBzVG2Zxb8c+5djQnpN4W35unqMvjD0w1TOuYNcQ5ptMldOhOzD23ypnt4t1QHgrtSHWcVri/8Q23RkWfwT/buFz1LXFaz+P2848rIgjvtdGqjDipk2hne0LT91/VhQ8rQTB2NZbkPXV0GJnOQIDE4EFh60n/wJTad+O4cCi4ODnjDNf24xcxPNGtrXWksTk42xEtXPRvrmfGtaeeDDE5zLNkjlcRIq2wcqTszQeSPsD8WH3b7rC2+G7KHWdMHj0SJktGi/+gtgAeoxdUEFU6kewojvf0V75pQKyoNVA6RMov3LHV1PYK8ium7CuIRgmDyaltbT7PCULXBgdbzEfJ12lsJ/gcaq7w+yuRpJC3jAdWoZlzMWrzWQWLMQrPTjd09IJmXE+k8wMxR3Hu+tzsQulIZvSfA=
  file: vifm.appimage
  on:
    tags: true
    condition: '("$CC" = clang) && ("$TRAVIS_OS_NAME" = linux)'
  skip_cleanup: 'true'
